"""empty message

Revision ID: 5d4409befce6
Revises: 
Create Date: 2021-10-26 23:48:58.844441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4409befce6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('Sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Snum', sa.Integer(), nullable=True),
    sa.Column('Sname', sa.String(length=30), nullable=False),
    sa.Column('Stel', sa.Integer(), nullable=True),
    sa.Column('Spwd', sa.String(length=30), nullable=False),
    sa.Column('Sschool', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('Sid')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('notice', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('Tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Tnum', sa.Integer(), nullable=True),
    sa.Column('Tname', sa.String(length=20), nullable=False),
    sa.Column('Tpwd', sa.String(length=30), nullable=True),
    sa.Column('Ttel', sa.Integer(), nullable=True),
    sa.Column('Tschool', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('Tid')
    )
    op.create_table('curriculum',
    sa.Column('Cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Cnum', sa.Integer(), nullable=True),
    sa.Column('Cname', sa.String(length=30), nullable=True),
    sa.Column('Cterm', sa.String(length=30), nullable=True),
    sa.Column('Tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Tid'], ['teacher.Tid'], ),
    sa.PrimaryKeyConstraint('Cid')
    )
    op.create_table('attendance',
    sa.Column('Aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Cid', sa.Integer(), nullable=False),
    sa.Column('Tid', sa.Integer(), nullable=False),
    sa.Column('Sid', sa.Integer(), nullable=False),
    sa.Column('isSuceess', sa.Boolean(), nullable=False),
    sa.Column('ADatetime', sa.DateTime(), nullable=True),
    sa.Column('Atime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Cid'], ['curriculum.Cid'], ),
    sa.ForeignKeyConstraint(['Sid'], ['student.Sid'], ),
    sa.ForeignKeyConstraint(['Tid'], ['teacher.Tid'], ),
    sa.PrimaryKeyConstraint('Aid')
    )
    op.create_table('student_curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.Cid'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.Sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_curriculum')
    op.drop_table('attendance')
    op.drop_table('curriculum')
    op.drop_table('teacher')
    op.drop_table('system')
    op.drop_table('student')
    # ### end Alembic commands ###
